/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task.scheduler;

import org.junit.Test;
import static org.junit.Assert.*;

public class SchedulerSchedulerAppTest {
    @Test
    public void testAppHasAGreeting() {

    }
}
